export type FoodOffer = {
  id: number;
  offer_title: string;
  restaurant_name: number;
  campaign_id: string;
  account_status: string;
  amount: string;
  banner_image: string;
  calendar_custom_days: number;
  created_at: string;
  credibility_range: string | null;
  currency_id: number;
  custom_btn_icon: string | null;
  custom_btn_title: string | null;
  custom_btn_url: string | null;
  date_valid_text: string | null;
  dedicated_offer_id: string | null;
  description: string;
  dress_code: string | null;
  email_text: string;
  end_date: string;
  end_offer_block: string | null;
  group_id: string | null;
  influencer_types: string | null;
  insight_required: number;
  instagram_followers: string;
  is_dedicated: number;
  is_groupX: number;
  is_offer_blogger: number;
  is_offer_dummy: number;
  is_offer_is_prive: number;
  is_offer_special: number;
  location_country_id: string | null;
  max_age: number;
  min_age: number;
  minimum_user_count: string | null;
  mobile_redemption_text: string | null;
  mobile_redemption_title: string | null;
  no_of_tables: string | null;
  notification_text: string | null;
  offer_available_end_date: string | null;
  offer_available_start_date: string | null;
  offer_display_end_time: string;
  offer_display_start_time: string;
  offer_end_time: string | null;
  offer_gender: string | null;
  offer_location: string | null;
  offer_notify: number;
  offer_start_time: string | null;
  offer_status: string;
  offer_usage: number;
  phone_campaign_mentions: string | null;
  phone_campaign_message: string | null;
  phone_review_comments: string | null;
  phone_review_text: string | null;
  reminder_custom_date: string;
  restaurant_website: string | null;
  review_url: string | null;
  rule_1: string;
  rule_2: string;
  rule_3: string;
  schedule_publish_time: string | null;
  skip_invitation: number;
  skip_stories: number;
  social_media_id: number;
  start_date: string;
  start_offer_block: string | null;
  updated_at: string;
  user_types: string;
  venue_offer_banner: number;
  whatsapp_no: string | null;
};

export type DedicatedOffer = {
  id: number;
  offer_title: string;
  venue_id: number;
  social_media_id: number;
  banner_image: string;
  offer_date: string;
  offer_usage: number;
  description: string;
  credibility_range: string | null;
  review_url: string | null;
  restaurant_website: string | null;
  whatsapp_no: string | null;
  amount: string;
  currency_id: number;
  instagram_followers: string;
  offer_status: number;
  offer_notify: number;
  minimum_user_count: string | null;
  no_of_tables: string | null;
  offer_gender: string;
  influencer_types: string;
  reminder_custom_date: string | null;
  skip_invitation: number;
  venue_update: number;
  is_published: number;
  min_age: number;
  max_age: number;
  user_types: string;
  is_offer_is_prive: number;
  is_offer_special: number;
  is_offer_instagram_verified: number;
  is_offer_blogger: number;
  offer_id: string | null;
  created_at: string;
  updated_at: string;
  offer_location: string | null;
  location_country_id: string | null;
  confirmation_message: string;
  schedule_publish_time: string | null;
  offer_start_time: string | null;
  offer_end_time: string | null;
  offer_display_start_time: string;
  offer_display_end_time: string;
  venue_offer_banner: number;
  is_offer_dummy: number;
};

export type Venue = {
  food_offers: FoodOffer[];
  dedicated_offers: DedicatedOffer[];
  category?: {
    id: number;
    category: string;
  };
};

export type Brand = {
  brandId: string;
  accountId: string | null;
  name: string;
  owner: string;
  logo: string | null;
  phoneNumber: string | null;
  emailAddress: string | null;
  industry: string | null;
  companyName: string | null;
  country: string | null;
  state: string | null;
  businessLocation: string | null;
  tradeLicenseCopy: string | File | null;
  vatCertificate: string | File | null;
  instagramHandle: string | null;
  websiteUrl: string | null;
  associateName: string | null;
  associateEmail: string | null;
  associatePhone: string | null;
  associateFirstName: string;
  associateLastName: string;
  associateInitials: string;
  associateBackground: string;
  registrationDate: string;
  offersCount: number;
  food_offers_count: number;
  campaignsCount: number;
  profileCompletion: number;
  files: number;
  Venue_contact_name: string | null;
  venue_email: string | null;
  Venue: Venue;
};